# Generated by Django 6.0.4 on 2026-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('date_of_birth', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
