# Generated by Django 6.0.4 on 2026-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='signin',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
