# Generated by Django 6.0.4 on 2026-06-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_book_name_order_book_price_order_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
    ]
